kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: finance-db-pvc
spec:
  {{- if .Values.storage.className }}
  storageClassName: {{ .Values.storage.className | quote }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
