apiVersion: v1
kind: Service
metadata:
  name: {{ include "financialplanner.fullname" . }}
  labels:
    {{- include "financialplanner.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ include "financialplanner.name" . }}
