replicaCount: 1
image:
  repository: ghcr.io/justinmarkmarshall/fplbot/financialplanner
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
# financeDb:
#   existingClaim: finance-db-pvc
#   mountPath: /app/data/finance.db
