replicaCount: 1
image:
  repository: ghcr.io/justinmarkmarshall/financialplanner.blazor
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
connectionStrings:
  financeDb: "Data Source=/app/data/finance.db"
storage:
  className: ""
ingress:
  enabled: true
  className: nginx
  host: financialplanner.marshalllab.uk
