replicaCount: 1
image:
  repository: ghcr.io/justinmarkmarshall/financialplanner.blazor
  tag: sha-4265ac1
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
connectionStrings:
  financeDb: "Data Source=/app/data/finance.db"
storage:
  className: ""
